#!/usr/bin/env python3
"""Download, clean and catalogue the brand logos shown in the app.

What it does
------------
* Holds the STARTING LIST of brands (``BRANDS`` below): id, accepted names and
  the source slug(s) to try.
* Downloads each logo from jsDelivr:
    - Simple Icons  (CC0-1.0)     -> preferred whenever the logo exists there
    - Dashboard Icons (Apache-2.0) -> only for brands missing from Simple Icons
* Cleans every SVG down to a monochrome silhouette:
  ``<svg xmlns=... viewBox=...>`` plus <path>/<polygon>/<rect>/<circle>/... only.
  No <title>, <style>, <script>, <defs>, width/height, class, style, fill,
  stroke or any colour: the page colours the logo (CSS mask-image).
* Discards logos that would render badly (full-size background shape, nothing
  left after cleaning, too big) and reports them.
* Writes:
    vedetta/app/static/ha/logos/<id>.svg
    vedetta/app/data/brand_logos.json

The script is idempotent: it can be re-run at any time; files are rewritten
only when their content changes, and stale files of ids no longer in the
resulting catalogue are removed.  Only the standard library is used.
Network access is required.

Usage:  python tools/update_logos.py
"""
import json
import re
import sys
import urllib.error
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOGO_DIR = ROOT / "vedetta" / "app" / "static" / "ha" / "logos"
JSON_PATH = ROOT / "vedetta" / "app" / "data" / "brand_logos.json"

SI_ICON = "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/{}.svg"
SI_DATA = "https://cdn.jsdelivr.net/npm/simple-icons@latest/data/simple-icons.json"
DI_ICON = "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons@main/svg/{}.svg"
DI_META = "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons@main/metadata.json"

MAX_BYTES = 12 * 1024
# Logos whose real shape fills the whole image (the big "a" of Amazon): checked by eye, not a solid background.
KEEP_FULL_SIZE = {"amazon"}

SOURCES = {
    "si": {"name": "Simple Icons", "license": "CC0-1.0",
           "url": "https://simpleicons.org"},
    "di": {"name": "Dashboard Icons", "license": "Apache-2.0",
           "url": "https://github.com/homarr-labs/dashboard-icons"},
}

COMMENT = (
    "Brand logo catalogue. id = file name in static/ha/logos/<id>.svg; "
    "names = every spelling the brand may appear with (the app compares them "
    "after removing everything that is not a letter or digit); source = "
    "'si:<slug>' (Simple Icons, CC0-1.0) or 'di:<name>' (Dashboard Icons, "
    "Apache-2.0); color = official brand colour (hex) or null. SVG files are "
    "cleaned monochrome silhouettes. Logos remain trademarks of their owners. "
    "Generated by tools/update_logos.py - do not edit by hand."
)

# (id, names, source kind, candidate slugs/names in order of preference)
BRANDS = [
    ("apple", ["Apple"], "si", ["apple"]),
    ("google", ["Google", "Google Nest", "Nest"], "si", ["google"]),
    ("samsung", ["Samsung"], "si", ["samsung"]),
    ("xiaomi", ["Xiaomi"], "si", ["xiaomi"]),
    ("huawei", ["Huawei"], "si", ["huawei"]),
    ("honor", ["Honor"], "si", ["honor"]),
    ("oneplus", ["OnePlus"], "si", ["oneplus"]),
    ("oppo", ["OPPO"], "si", ["oppo"]),
    ("vivo", ["vivo"], "si", ["vivo"]),
    ("sony", ["Sony"], "si", ["sony"]),
    ("lg", ["LG"], "si", ["lg"]),
    ("asus", ["ASUS"], "si", ["asus"]),
    ("acer", ["Acer"], "si", ["acer"]),
    ("dell", ["Dell"], "si", ["dell"]),
    ("hp", ["HP"], "si", ["hp"]),
    ("lenovo", ["Lenovo"], "si", ["lenovo"]),
    ("msi", ["MSI"], "si", ["msi"]),
    ("razer", ["Razer"], "si", ["razer"]),
    ("tplink", ["TP-Link", "TPLink"], "si", ["tplink", "tp-link"]),
    ("netgear", ["Netgear"], "si", ["netgear"]),
    ("mikrotik", ["MikroTik"], "si", ["mikrotik"]),
    ("ubiquiti", ["Ubiquiti"], "si", ["ubiquiti"]),
    ("fritz", ["AVM", "FRITZ!", "Fritz", "FRITZ!Box", "Fritz!Box"], "si",
     ["avm", "fritz", "fritzbox"]),
    ("synology", ["Synology"], "si", ["synology"]),
    ("qnap", ["QNAP"], "si", ["qnap"]),
    ("shelly", ["Shelly"], "si", ["shelly"]),
    ("tasmota", ["Tasmota"], "si", ["tasmota"]),
    ("esphome", ["ESPHome"], "si", ["esphome"]),
    ("sonos", ["Sonos"], "si", ["sonos"]),
    ("roku", ["Roku"], "si", ["roku"]),
    ("epson", ["Epson"], "si", ["epson"]),
    ("philipshue", ["Philips Hue", "Hue"], "si", ["philipshue", "philips-hue"]),
    ("ikea", ["IKEA"], "si", ["ikea"]),
    ("ring", ["Ring"], "si", ["ring"]),
    ("pihole", ["Pi-hole", "Pihole"], "si", ["pihole", "pi-hole"]),
    ("raspberrypi", ["Raspberry Pi"], "si", ["raspberrypi", "raspberry-pi"]),
    ("homeassistant", ["Home Assistant"], "si", ["homeassistant", "home-assistant"]),
    ("proxmox", ["Proxmox"], "si", ["proxmox"]),
    ("nodered", ["Node-RED"], "si", ["nodered", "node-red"]),
    ("grafana", ["Grafana"], "si", ["grafana"]),
    ("adguard", ["AdGuard"], "si", ["adguard"]),
    ("bose", ["Bose"], "si", ["bose"]),
    ("jbl", ["JBL"], "si", ["jbl"]),
    ("kyocera", ["Kyocera"], "si", ["kyocera"]),
    ("openwrt", ["OpenWrt"], "si", ["openwrt"]),
    ("vmware", ["VMware"], "si", ["vmware"]),
    ("truenas", ["TrueNAS"], "si", ["truenas"]),
    ("cisco", ["Cisco"], "si", ["cisco"]),
    ("zigbee2mqtt", ["Zigbee2MQTT"], "si", ["zigbee2mqtt"]),
    # Dashboard Icons (only where Simple Icons has nothing)
    ("amazon", ["Amazon"], "di", ["amazon"]),
    ("microsoft", ["Microsoft"], "di", ["microsoft"]),
    ("unifi", ["UniFi"], "di", ["unifi"]),
    ("hikvision", ["Hikvision", "HiWatch"], "di", ["hikvision"]),
    ("dahua", ["Dahua", "Imou"], "di", ["dahua"]),
    ("amcrest", ["Amcrest"], "di", ["amcrest"]),
    ("reolink", ["Reolink"], "di", ["reolink"]),
    ("foscam", ["Foscam"], "di", ["foscam"]),
    ("d-link", ["D-Link", "DLink"], "di", ["d-link", "dlink"]),
    ("brother", ["Brother"], "di", ["brother"]),
    ("axis", ["Axis"], "di", ["axis"]),
    ("asustor", ["Asustor"], "di", ["asustor"]),
    ("tenda", ["Tenda"], "di", ["tenda"]),
    ("terramaster", ["TerraMaster"], "di", ["terramaster"]),
    ("lexmark", ["Lexmark"], "di", ["lexmark"]),
    ("ricoh", ["Ricoh"], "di", ["ricoh"]),
    ("netatmo", ["Netatmo"], "di", ["netatmo"]),
]

SVG_NS = "http://www.w3.org/2000/svg"
SHAPES = {"path", "polygon", "polyline", "rect", "circle", "ellipse"}
# attributes kept on shape elements (geometry only, no colour/style)
GEOM_ATTRS = {
    "path": ["d"], "polygon": ["points"], "polyline": ["points"],
    "rect": ["x", "y", "width", "height", "rx", "ry"],
    "circle": ["cx", "cy", "r"], "ellipse": ["cx", "cy", "rx", "ry"],
}
FILL_RULE_ATTRS = ["fill-rule", "clip-rule"]


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "vedetta-update-logos"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def try_fetch(url):
    try:
        return fetch(url)
    except (urllib.error.URLError, OSError):
        return None


# --------------------------------------------------------------------------
# colour helpers
# --------------------------------------------------------------------------
NAMED = {"white": "#ffffff", "black": "#000000"}


def norm_color(c):
    """Return '#rrggbb', or None for none/url()/unknown/currentColor."""
    if not c:
        return None
    c = c.strip().lower()
    c = NAMED.get(c, c)
    m = re.fullmatch(r"#([0-9a-f]{3})", c)
    if m:
        return "#" + "".join(ch * 2 for ch in m.group(1))
    if re.fullmatch(r"#[0-9a-f]{6}", c):
        return c
    m = re.fullmatch(r"rgb\(\s*(\d+)[ ,]+(\d+)[ ,]+(\d+)\s*\)", c)
    if m:
        return "#%02x%02x%02x" % tuple(min(255, int(x)) for x in m.groups())
    return None


def is_white(c):
    return c is not None and all(int(c[i:i + 2], 16) >= 0xF0 for i in (1, 3, 5))


def is_blackish(c):
    return c is not None and all(int(c[i:i + 2], 16) <= 0x20 for i in (1, 3, 5))


def local(tag):
    return tag.rsplit("}", 1)[-1]


def style_props(el):
    props = {}
    for part in (el.get("style") or "").split(";"):
        if ":" in part:
            k, v = part.split(":", 1)
            props[k.strip().lower()] = v.strip()
    return props


def paint(el, name):
    """Own value of a paint property (attribute or inline style)."""
    sp = style_props(el)
    return sp.get(name, el.get(name))


def css_fills(root):
    """Very small CSS reader for <style> blocks: {class: fill}."""
    out = {}
    for st in root.iter():
        if local(st.tag) == "style" and st.text:
            for m in re.finditer(r"\.([\w-]+)\s*\{([^}]*)\}", st.text):
                f = re.search(r"fill\s*:\s*([^;}\s]+)", m.group(2))
                if f:
                    out[m.group(1)] = f.group(1)
    return out


def gradient_first_stop(root):
    """{gradient id: first stop colour}"""
    out = {}
    for g in root.iter():
        if local(g.tag) in ("linearGradient", "radialGradient") and g.get("id"):
            for s in g.iter():
                if local(s.tag) == "stop":
                    c = norm_color(paint(s, "stop-color"))
                    if c:
                        out[g.get("id")] = c
                        break
    return out


# --------------------------------------------------------------------------
# cleaning
# --------------------------------------------------------------------------
class Discard(Exception):
    pass


def fmt(n):
    s = ("%.3f" % n).rstrip("0").rstrip(".")
    return s or "0"


def parse_viewbox(root):
    vb = root.get("viewBox")
    if vb:
        nums = [float(x) for x in re.split(r"[ ,]+", vb.strip())]
        if len(nums) == 4:
            return nums
    w = re.sub(r"[a-z%]+$", "", (root.get("width") or "").strip())
    h = re.sub(r"[a-z%]+$", "", (root.get("height") or "").strip())
    if w and h:
        return [0.0, 0.0, float(w), float(h)]
    raise Discard("no viewBox")


def covers_viewbox(el, vb):
    """True if a rect/circle/ellipse fills (nearly) the whole viewBox."""
    t = local(el.tag)
    x0, y0, w, h = vb
    try:
        if t == "rect":
            ew = float(el.get("width", 0)); eh = float(el.get("height", 0))
            ex = float(el.get("x", 0)); ey = float(el.get("y", 0))
            return ew >= 0.9 * w and eh >= 0.9 * h and ex <= x0 + 0.05 * w and ey <= y0 + 0.05 * h
        if t == "circle":
            return float(el.get("r", 0)) * 2 >= 0.9 * min(w, h)
        if t == "ellipse":
            return float(el.get("rx", 0)) * 2 >= 0.9 * w and float(el.get("ry", 0)) * 2 >= 0.9 * h
    except ValueError:
        pass
    return False


def path_bbox_covers(el, vb):
    """Heuristic for a background <path> (rounded square / circle):
    bounding box of its absolute coordinates spans nearly the whole viewBox
    AND the path has few commands."""
    d = el.get("d", "")
    if len(re.findall(r"[A-Za-z]", d)) > 14:
        return False
    # only trust absolute-coordinate paths
    if re.search(r"[mlhvcsqtaz]", d.replace("e", "")) and not re.search(r"[MLHVCSQTAZ]", d):
        return False
    nums = [float(n) for n in re.findall(r"-?\d*\.?\d+(?:e-?\d+)?", d)]
    if len(nums) < 4:
        return False
    xs, ys = nums[0::2], nums[1::2]
    x0, y0, w, h = vb
    return (max(xs) - min(xs) >= 0.95 * w) and (max(ys) - min(ys) >= 0.95 * h)


def clean_svg(raw, is_simple_icons, keep_full_size=False):
    """Return (clean_svg_text, dominant_colour_or_None). Raises Discard."""
    text = raw.decode("utf-8", "replace")
    text = re.sub(r"<!DOCTYPE[^>]*>|<\?xml[^>]*\?>|<!--.*?-->", "", text, flags=re.S)
    try:
        root = ET.fromstring(text)
    except ET.ParseError as e:
        raise Discard("unparseable SVG (%s)" % e)
    if local(root.tag) != "svg":
        raise Discard("not an SVG")
    vb = parse_viewbox(root)
    classes = css_fills(root)
    grads = gradient_first_stop(root)
    kept = []
    colours = []
    dropped_white = 0

    def eff_fill(el, inherited):
        f = paint(el, "fill")
        if f is None and el.get("class"):
            for cl in el.get("class").split():
                if cl in classes:
                    f = classes[cl]
        return inherited if f is None else f

    def walk(el, inherited_fill, tf):
        nonlocal dropped_white
        t = local(el.tag)
        if t in ("defs", "style", "script", "title", "desc", "metadata",
                 "clipPath", "mask", "linearGradient", "radialGradient",
                 "filter", "pattern", "image", "text", "symbol"):
            return
        fill = eff_fill(el, inherited_fill)
        own_tf = el.get("transform")
        cur_tf = (tf + " " + own_tf).strip() if own_tf else tf
        if t == "g":
            for ch in el:
                walk(ch, fill, cur_tf)
            return
        if t not in SHAPES:
            return
        if (paint(el, "display") or "").strip() == "none":
            return
        fl = (fill or "black").strip()
        if fl == "none":
            return  # stroke-only / invisible: cannot be a silhouette
        op = paint(el, "opacity") or paint(el, "fill-opacity")
        if op is not None and op.strip() not in ("1", "1.0"):
            try:
                if float(op) < 0.5:
                    return
            except ValueError:
                pass
        col = None
        m = re.fullmatch(r"url\(#?['\"]?([^)'\"]+)['\"]?\)", fl)
        if m:
            col = grads.get(m.group(1))
        else:
            col = norm_color(fl)
        if is_white(col):
            dropped_white += 1
            return
        if not is_simple_icons and not keep_full_size and (covers_viewbox(el, vb) or
                                    (t == "path" and path_bbox_covers(el, vb))):
            raise Discard("full-size background shape")
        if col and not is_blackish(col):
            colours.append(col)
        elif col is None and not m:
            colours.append(None)
        attrs = []
        for a in GEOM_ATTRS[t]:
            if el.get(a) is not None:
                attrs.append('%s="%s"' % (a, re.sub(r"\s+", " ", el.get(a).strip())))
        for a in FILL_RULE_ATTRS:
            v = paint(el, a)
            if v:
                attrs.append('%s="%s"' % (a, v))
        if cur_tf:
            attrs.append('transform="%s"' % cur_tf)
        if not any(a.startswith(GEOM_ATTRS[t][0] + "=") for a in attrs):
            return
        kept.append("<%s %s/>" % (t, " ".join(attrs)))

    for ch in root:
        walk(ch, None, "")
    if not kept:
        raise Discard("nothing left after cleaning")
    vbs = " ".join(fmt(n) for n in vb)
    out = '<svg xmlns="%s" viewBox="%s">%s</svg>\n' % (SVG_NS, vbs, "".join(kept))
    dom = None
    for c in colours:
        if c:
            dom = c
            break
    return out, dom


# --------------------------------------------------------------------------
# main
# --------------------------------------------------------------------------
def write_if_changed(path, data, binary=False):
    mode = "wb" if binary else "w"
    if path.exists():
        old = path.read_bytes()
        new = data if binary else data.encode("utf-8")
        if old == new:
            return False
    path.parent.mkdir(parents=True, exist_ok=True)
    if binary:
        path.write_bytes(data)
    else:
        path.write_text(data, encoding="utf-8", newline="\n")
    return True


def main():
    si_hex = {}
    raw = try_fetch(SI_DATA)
    if raw:
        for ic in json.loads(raw.decode("utf-8")):
            si_hex[ic.get("slug") or ""] = ic.get("hex")
            # slug is not always present in older data; fall back to title
            title = re.sub(r"[^a-z0-9]", "", ic.get("title", "").lower())
            si_hex.setdefault(title, ic.get("hex"))
    else:
        print("WARNING: Simple Icons metadata not reachable; colours will be null")
    di_meta = {}
    raw = try_fetch(DI_META)
    if raw:
        di_meta = json.loads(raw.decode("utf-8"))

    logos, downloaded, missing, discarded, big = [], [], [], [], []
    for bid, names, kind, cands in BRANDS:
        svg, colour, src, why = None, None, None, None
        for slug in cands:
            if kind == "di" and di_meta and di_meta.get(slug, {}).get("base") not in (None, "svg"):
                why = "Dashboard Icons has only a %s version (no SVG)" % di_meta[slug].get("base")
                continue
            data = try_fetch((SI_ICON if kind == "si" else DI_ICON).format(slug))
            if data is None:
                why = why or "not found (tried: %s)" % ", ".join(cands)
                continue
            try:
                svg, dom = clean_svg(data, kind == "si", keep_full_size=bid in KEEP_FULL_SIZE)
            except Discard as e:
                discarded.append((bid, str(e)))
                svg = None
                why = None
                break
            src = "%s:%s" % (kind, slug)
            if kind == "si":
                h = si_hex.get(slug)
                colour = ("#" + h.upper()) if h else None
            else:
                colour = dom.upper() if dom else None
            break
        else:
            pass
        if svg is None:
            if why:
                missing.append((bid, why))
            continue
        size = len(svg.encode("utf-8"))
        if size > MAX_BYTES:
            big.append((bid, size))
            discarded.append((bid, "larger than %d KB (%d bytes)" % (MAX_BYTES // 1024, size)))
            continue
        write_if_changed(LOGO_DIR / (bid + ".svg"), svg)
        logos.append({"id": bid, "names": names, "source": src, "color": colour})
        downloaded.append(bid)

    # remove stale files of ids that are not in the catalogue any more
    keep = {l["id"] + ".svg" for l in logos}
    if LOGO_DIR.exists():
        for f in LOGO_DIR.glob("*.svg"):
            if f.name not in keep:
                f.unlink()

    doc = {"schema": 1, "_comment": COMMENT, "sources": SOURCES, "logos": logos}
    write_if_changed(JSON_PATH, json.dumps(doc, indent=1, ensure_ascii=False) + "\n")

    print("Downloaded: %d (si: %d, di: %d)" % (
        len(logos), sum(l["source"].startswith("si:") for l in logos),
        sum(l["source"].startswith("di:") for l in logos)))
    print("Missing:    %d" % len(missing))
    for b, w in missing:
        print("  - %s: %s" % (b, w))
    print("Discarded:  %d" % len(discarded))
    for b, w in discarded:
        print("  - %s: %s" % (b, w))
    return 0


if __name__ == "__main__":
    sys.exit(main())
